routes:
  /tag/midnight-radio/:
    template: page-radio
    redirect: /radio
  /favorites/:
    template: page-favorites 
  /art-diary/:
    template: page-art-diary 
  /notebook/:
    template: page-notebook

collections:
  # Notebook collections
  /god/:
    permalink: /god/{slug}/
    template: tag-notebook-collection
    filter: tag:god
    data: tag.god
    
  /weather/:
    permalink: /weather/{slug}/
    template: tag-notebook-collection
    filter: tag:weather
    data: tag.weather
    
  /dreams/:
    permalink: /dreams/{slug}/
    template: tag-notebook-collection
    filter: tag:dreams
    data: tag.dreams

  # Other collections
  /broadcasts/:
    permalink: /broadcasts/{slug}/
    filter: tag:broadcasts
    template: tag-broadcasts
    data: tag.broadcasts
    
  /design/:
    permalink: /design/{slug}/
    filter: tag:design
    template: tag-design
    data: tag.design
    
  /art/:
    permalink: /art/{slug}/
    filter: tag:artwork
    template: tag-artwork
    data: tag.artwork
    
  /books/:
    permalink: /books/{slug}/
    filter: tag:books
    template: tag-books
    data: tag.books

  # Root collection (homepage)
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/